language: node_js
node_js:
- '0.12'
before_script:
- npm install -g grunt-cli
script:
- grunt jshint
sudo: false
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  api_key:
    secure: mwDzaP0gmD0f+McfuT+MTFgCsTxsRtB/GDCq6FvaGEbRLF+Lxh8aT+Cb9+K7Whyw1JZFPMoJgr3agEPviNcWq4WHBeEs4m7UTgk1qw69jkiq7XWIkrzGYPEZbfOIhV4WI5+R0Kagi5y/G+F3B27LpLglAf/eoX8EPX5upXsD2Ek=
  on:
    tags: true
    all_branches: true
    repo: scurker/currency.js
  email:
    secure: bGqxxzNYHojWnTJ2VZ2AmzMfQVegYFbrn9ngn5TxvLWUGByWDcaZZKpCahi+ACBRxium+r8jbiPrQR6C47uXqsKEdYB+LK83ZbxObahD1IsbzBgR+5T/BmCoxdQtsjbhEbq2GeLTpPQDjWbwk0qFbvwajxt/x1cvF+IfClKEx+U=
