language: node_js
node_js:
- '0.12'
- '4.1'
before_install:
- npm install -g grunt-cli coveralls
script:
- grunt jshint
- npm run test
sudo: false
cache:
  directories:
  - node_modules
after_success:
  - npm run coverage
  - cat reports/lcov.info | coveralls
deploy:
  provider: npm
  email:
    secure: E5X6CQNG5Qj32TVZv6OJRFtaXZKSBd9fR/u20yWZik1BCpGNzQ9A42+xXkjliHWwu7n2Xh482iaqgiv00NWVzPMaycFVJrF7SPHDl08SH6p/R5DvgLQV79ISBtEwHxzDC3hrJOeVFknZMKaGo+TUQXiL7CYVnHMxHqlTDNJKh6g=
  api_key:
    secure: NJogJXmMUaBUV2T9gdeNph+mMy72ZKh2yyeqywkLWejfUuISo93LI6Zbe6Irs9ouXlF2olcFMqWxOjxc//UoCICizwq/LQUd4X6mB2/Kob2joSqKQG1VAnqNj6dkTAYaNPXrf/FSoW5GljwCjss/lBioSOfIHQhn6omGI9Ecf7E=
  on:
    tags: true
    repo: scurker/currency.js
